version: "3"
services:
    firestrom:
        container_name: "firestrom"
        runtime: nvidia
        build: ./
        volumes:
            - ./app:/workspace/app
            - ./app/images:/images
            - ./darknet:/workspace
        ports:
            - "81:80"